# modules/roman_normalizer.py
"""
Convert Roman Urdu queries to standard Urdu script.
"""

# Core mapping (expand as needed)
ROMAN_MAP = {
    "pyar": "پیار",
    "pyaar": "پیار",
    "mohabbat": "محبت",
    "ishq": "عشق",
    "tum": "تم",
    "mein": "میں",
    "main": "میں",
    "dil": "دل",
    "dill": "دل",
    "gham": "غم",
    "qareeb": "قریب",
    "kar": "کر",
    "karo": "کرو",
    "aao": "آؤ",
    "raat": "رات",
    "khwab": "خواب",
    "khawab": "خواب",
    "yaad": "یاد",
    "zindagi": "زندگی",
    "mout": "موت",
    "jaan": "جان",
    "rooh": "روح",
    "dard": "درد",
    "sukoon": "سکون",
    "tanhai": "تنہائی",
    "doori": "دوری",
    "wafa": "وفا",
    "bewafai": "بے وفائی",
    "aansoo": "آنسو",
    "khushi": "خوشی",
    "ghazal": "غزل",
    "shayar": "شاعر",
    "shayari": "شاعری",
   "mohabbat": "محبت",
    "ishq": "عشق",
    "pyar": "پیار",
    "dard": "درد",
    "zindagi": "زندگی",
    "raat": "رات",
    "tanhaai": "تنہائی",
    "yaad": "یاد",
    "dil": "دل",
    "aankh": "آنکھ",
    "lab": "لب",
    "chehra": "چہرہ",
    "husan": "حسن",
    "khuda": "خدا",
    "safar": "سفر",
    "manzil": "منزل",
    "dunya": "دنیا",
    "gham": "غم",
    "aansu": "آنسو",
    "jaan": "جان",
    "night": "رات",
    "love": "محبت",
    "lonely": "تنہائی",
    "sad": "غم",
    "heart": "دل",
    "life": "زندگی",
    "death": "موت",
    "moon": "چاند",
    "flower": "پھول",
    "pain": "درد",
    "hope": "امید",
    "waiting": "انتظار",

    # Numbers 1–20
    "ek": "ایک",
    "do": "دو",
    "teen": "تین",
    "chaar": "چار",
    "paanch": "پانچ",
    "chhe": "چھے",
    "saat": "سات",
    "aath": "آٹھ",
    "nau": "نو",
    "das": "دس",
    "gyaarah": "گیارہ",
    "baarah": "بارہ",
    "terah": "تیرہ",
    "chaudah": "چودہ",
    "pandrah": "پندرہ",
    "solah": "سولہ",
    "satrah": "سترہ",
    "athaarah": "اٹھارہ",
    "unnis": "انیس",
    "bees": "بیس",

    # Days
    "itwaar": "اتوار",
    "peer": "پیر",
    "mangal": "منگل",
    "budh": "بدھ",
    "jumerat": "جمعرات",
    "jummah": "جمعہ",
    "hafta": "ہفتہ",

    # Months
    "muharram": "محرم",
    "safar_month": "صفر",
    "rabiul_awwal": "ربیع الاول",
    "rabiul_saani": "ربیع الثانی",
    "jamadiul_awwal": "جمادی الاول",
    "jamadiul_saani": "جمادی الثانی",
    "rajab": "رجب",
    "shabaan": "شعبان",
    "ramadan": "رمضان",
    "shawwal": "شوال",
    "zilqadah": "ذوالقعدہ",
    "zilhijjah": "ذوالحجہ",
    "janvari": "جنوری",
    "farvari": "فروری",
    "march": "مارچ",
    "april": "اپریل",
    "may": "مئی",
    "june": "جون",
    "july": "جولائی",
    "august": "اگست",
    "september": "ستمبر",
    "october": "اکتوبر",
    "november": "نومبر",
    "december": "دسمبر",

    # Colors
    "laal": "لال",
    "neela": "نیلا",
    "hara": "ہرا",
    "peela": "پیلا",
    "safed": "سفید",
    "kala": "کالا",
    "bhoora": "بھورا",
    "narangi": "نارنجی",
    "gulabi": "گلابی",
    "jamuni": "جامنی",
    "khaki": "خاکی",
    "chandi": "چاندی",
    "sona": "سونا",
    "aasmani": "آسمانی",
    "firozi": "فیروزی",

    # Family
    "maan": "ماں",
    "baap": "باپ",
    "bhai": "بھائی",
    "behan": "بہن",
    "beta": "بیٹا",
    "beti": "بیٹی",
    "khawand": "خاوند",
    "biwi": "بیوی",
    "dada": "دادا",
    "dadi": "دادی",
    "nana": "نانا",
    "nani": "نانی",
    "chaacha": "چچا",
    "chaachi": "چچی",
    "mamoon": "ماموں",
    "mami": "مامی",
    "khaloo": "خالو",
    "khala": "خالہ",
    "bhatija": "بھتیجا",
    "bhatiji": "بھتیجی",

    # Body parts
    "sar": "سر",
    "baal": "بال",
    "maatha": "ماتھا",
    "bhaun": "بھوں",
    "palken": "پلکیں",
    "naak": "ناک",
    "kaan": "کان",
    "gal": "گال",
    "moo": "منہ",
    "daant": "دانٹ",
    "zaban": "زبان",
    "gardan": "گردن",
    "kandha": "کندھا",
    "baazu": "بازو",
    "haath": "ہاتھ",
    "ungli": "انگلی",
    "khushoona": "خشونہ",
    "seenah": "سینہ",
    "peeth": "پیٹھ",
    "pait": "پیٹ",
    "tang": "ٹانگ",
    "ghutna": "گھٹنا",
    "pair": "پیر",
    "jism": "جسم",
    "khoon": "خون",

    # Nature
    "suraj": "سورج",
    "chand": "چاند",
    "sitara": "ستارہ",
    "aasmaan": "آسمان",
    "zameen": "زمین",
    "hawa": "ہوا",
    "paani": "پانی",
    "aag": "آگ",
    "barf": "برف",
    "badal": "بادل",
    "barsaat": "بارش",
    "bijli": "بجلی",
    "dhoop": "دھوپ",
    "chaon": "چھاؤں",
    "kohar": "کوہر",
    "dhund": "دھند",
    "jharna": "جھرنا",
    "nadi": "ندی",
    "samandar": "سمندر",
    "pahaar": "پہاڑ",
    "jangal": "جنگل",
    "raasta": "راستہ",
    "bagh": "باغ",
    "phool": "پھول",
    "pattha": "پتھر",
    "mitti": "مٹی",
    "ghaas": "گھاس",
    "darakht": "درخت",
    "patta": "پتہ",
    "bij": "بیج",

    # Emotions
    "khushi": "خوشی",
    "udasi": "اداسی",
    "ghussa": "غصہ",
    "pyaar": "پیار",
    "nफरत": "نفرت",
    "irshaad": "ارشاد",
    "jazbaat": "جذبات",
    "josh": "جوش",
    "sukoon": "سکون",
    "bebasi": "بے بسی",
    "majboori": "مجبوری",
    "umeed": "امید",
    "na_umeedi": "ناامیدی",
    "tashweesh": "تشویش",
    "fear": "خوف",
    "andshesha": "اندیشہ",
    "hairat": "حیرت",
    "sharm": "شرم",
    "ghuroor": "غرور",
    "hassad": "حسد",
    "rahmat": "رحمت",
    "shafqat": "شفقت",
    "wafa": "وفا",
    "bewafai": "بے وفائی",
    "judai": "جدائی",
    "wasl": "وصل",
    "hijr": "ہجر",
    "khamoshi": "خاموشی",
    "shiddat": "شدت",

    # Verbs
    "karna": "کرنا",
    "hona": "ہونا",
    "jana": "جانا",
    "aana": "آنا",
    "dena": "دینا",
    "lena": "لینا",
    "bolna": "بولنا",
    "sona": "سونا",
    "jagna": "جگنا",
    "khana": "کھانا",
    "peena": "پینا",
    "rona": "رونا",
    "hansna": "ہنسنا",
    "parhna": "پڑھنا",
    "likhna": "لکھنا",
    "chalna": "چلنا",
    "daurna": "دوڑنا",
    "baithna": "بیٹھنا",
    "uthna": "اٹھنا",
    "dekna": "دیکھنا",
    "sunna": "سننا",
    "sochna": "سوچنا",
    "samajhna": "سمجھنا",
    "poochna": "پوچھنا",
    "batana": "بتانا",
    "milna": "ملنا",
    "khelna": "کھیلنا",
    "nahaana": "نہانا",
    "kapre_pehenna": "کپڑے پہننا",
    "nikaalna": "نکالنا",
    "daalna": "ڈالنا",
    "todna": "توڑنا",
    "jodna": "جوڑنا",
    "khareedna": "خریدنا",
    "bechna": "بیچنا",
    "jeetna": "جیتنا",
    "haarna": "ہارنا",
    "banna": "بنا",
    "bighadna": "بگڑنا",
    "rukna": "رکنا",
    "chalna_phirna": "چلنا پھرنا",
    "ghumna": "گھومنا",
    "thakna": "تھکنا",
    "aaraam_karna": "آرام کرنا",
    "ro_kar_karna": "رو کر کرنا",
    "hans_kar_karna": "ہنس کر کرنا",
    "manna": "ماننا",
    "inkaar_karna": "انکار کرنا",
    "wada_karna": "وعدہ کرنا",
    "nibhana": "نبانا",

    # Adjectives
    "acha": "اچھا",
    "bura": "برا",
    "khoobsurat": "خوبصورت",
    "baddar": "بدصورت",
    "naya": "نیا",
    "purana": "پرانا",
    "garam": "گرم",
    "thanda": "ٹھنڈا",
    "meetha": "میٹھا",
    "khatta": "کھٹا",
    "namkeen": "نمکین",
    "taza": "تازہ",
    "purzoor": "پرزور",
    "kamzor": "کمزور",
    "amir": "امیر",
    "ghareeb": "غریب",
    "khush": "خوش",
    "udaas": "اداس",
    "poraana": "پُرانا",
    "jadeed": "جدید",
    "buland": "بلند",
    "pust": "پست",
    "roshan": "روشن",
    "andhera": "اندھیرا",
    "tez": "تیز",
    "ahista": "آہستہ",
    "saf": "صاف",
    "ganda": "گندا",
    "sona": "سونا",
    "chandi_jaisa": "چاندی جیسا",
    "pukhta": "پختہ",
    "kacha": "کچا",
    "sakht": "سخت",
    "naram": "نرم",
    "bhaari": "بھاری",
    "halka": "ہلکا",
    "lambi": "لمبی",
    "chhoti": "چھوٹی",
    "mota": "موٹا",
    "patla": "پتلا",
    "rangeen": "رنگین",
    "be_rang": "بے رنگ",
    "mahanga": "مہنگا",
    "sasta": "سستا",
    "dumdaar": "دمدار",
    "bewaqoof": "بیوقوف",
    "hoshyaar": "ہوشیار",
    "tajurba_kaar": "تجربہ کار",
    "na_tajurba_kaar": "نا تجربہ کار",

    # Food
    "roti": "روٹی",
    "chawal": "چاول",
    "daal": "دال",
    "sabzi": "سبزی",
    "ghosht": "گوشت",
    "murghi": "مرغی",
    "machli": "مچھلی",
    "anda": "انڈہ",
    "doodh": "دودھ",
    "dahi": "دہی",
    "panir": "پنیر",
    "makhan": "مکھن",
    "shakar": "شکر",
    "namak": "نمک",
    "mirch": "مرچ",
    "haldi": "ہلدی",
    "zeera": "زیرہ",
    "chatni": "چٹنی",
    "achar": "اچار",
    "samosa": "سموسہ",
    "pakora": "پکوڑا",
    "biryani": "بریانی",
    "qorma": "قورمہ",
    "kebab": "کباب",
    "nihari": "نہاری",
    "haleem": "حلیم",
    "paye": "پائے",
    "kheer": "کھیر",
    "falooda": "فلودہ",
    "jalebi": "جلیبی",

    # Household
    "darwaza": "دروازہ",
    "kirkhi": "کھڑکی",
    "kamra": "کمرہ",
    "bistar": "بستر",
    "takya": "تکیہ",
    "chaadar": "چادر",
    "kursi": "کرسی",
    "mez": "میز",
    "almari": "الماری",
    "sofa": "سوفہ",
    "farsh": "فرش",
    "dari": "داری",
    "pankha": "پنکھا",
    "bulb": "بلب",
    "barat_numa": "برات نما",
    "batari": "بٹری",
    "chulha": "چولہا",
    "tawa": "توہ",
    "deg": "دیگ",
    "karahi": "کراہی",
    "chammach": "چمچ",
    "kaanta": "کانٹا",
    "chaku": "چاقو",
    "glass": "گلاس",
    "pyala": "پیالہ",
    "surahi": "سوراہی",
    "dastarkhwan": "دسترخوان",
    "kalaam": "قلم",
    "kaghaz": "کاغذ",
    "kitab": "کتاب",

    # Clothing
    "kapray": "کپڑے",
    "qameez": "قمیض",
    "pajama": "پاجامہ",
    "shalwar": "شلوار",
    "dupatta": "دوپٹہ",
    "burqa": "برقع",
    "topi": "ٹوپی",
    "jaacket": "جیکٹ",
    "coat": "کوٹ",
    "sweater": "سویٹر",
    "joota": "جوتا",
    "mojari": "موجاری",
    "chappal": "چپل",
    "shoes": "شوز",
    "lungi": "لنگی",
    "tie": "ٹائی",
    "belt": "بیلٹ",
    "ring": "انگوٹھی",
    "choori": "چوڑی",
    "hath_kari": "ہاتھ کاری",

    # Time
    "subah": "صبح",
    "shaam": "شام",
    "din": "دن",
    "ghadi": "گھڑی",
    "pal": "پل",
    "lamha": "لمحہ",
    "saal": "سال",
    "mahina": "مہینہ",
    "hafta_block": "ہفتہ",
    "ghanta": "گھنٹہ",
    "minute": "منٹ",
    "second": "سیکنڈ",
    "aaj": "آج",
    "kal": "کل",
    "parson": "پرسوں",
    "teesra_din": "تیسرا دن",
    "hafta_baar": "ہفتہ بھر",
    "mahina_baar": "مہینہ بھر",
    "saal_baar": "سال بھر",
    "hamesha": "ہمیشہ",

    # Directions
    "shumal": "شمال",
    "janob": "جنوب",
    "mashriq": "مشرق",
    "maghrib": "مغرب",
    "utra": "اتر",
    "dakhan": "دکھن",
    "dayen": "دائیں",
    "bayein": "بائیں",
    "seedha": "سیدھا",
    "peechay": "پیچھے",
    "aage": "آگے",

    # Pronouns
    "main": "میں",
    "tum": "تم",
    "tuu": "تو",
    "aap": "آپ",
    "hum": "ہم",
    "woh": "وہ",
    "yeh": "یہ",
    "apna": "اپنا",
    "khud": "خود",
    "kisi": "کسی",
    "kuch": "کچھ",
    "sab": "سب",

    # Prepositions
    "ko": "کو",
    "se": "سے",
    "par": "پر",
    "tak": "تک",
    "liye": "لیے",
    "baad": "بعد",
    "pehle": "پہلے",
    "andar": "اندر",
    "bahar": "باہر",
    "paas": "پاس",
    "door": "دور",
    "aur": "اور",
    "ya": "یا",
    "lekin": "لیکن",
    "kyunke": "کیونکہ",
    "agar": "اگر",
    "toh": "تو",
    "warna": "ورنہ",

    # Common nouns
    "insaan": "انسان",
    "aurat": "عورت",
    "mard": "مرد",
    "bacha": "بچہ",
    "larki": "لڑکی",
    "larka": "لڑکا",
    "dost": "دوست",
    "duShman": "دشمن",
    "ustaad": "استاد",
    "shagird": "شاگرد",
    "doctor": "ڈاکٹر",
    "engineer": "انجینئر",
    "kaam": "کام",
    "office": "دفتر",
    "school": "اسکول",
    "college": "کالج",
    "university": "یونیورسٹی",
    "masjid": "مسجد",
    "mandir": "مندر",
    "girja": "گرجا",
    "bazar": "بازار",
    "gali": "گلی",
    "mohalla": "محلہ",
    "shehar": "شہر",
    "gaon": "گاؤں",
    "park": "پارک",
    "hospital": "ہسپتال",
    "police": "پولیس",
    "court": "عدالت",
    "qanon": "قانون",

    # Poetic / literary
    "ulfat": "الفت",
    "nigaah": "نگاہ",
    "nazar": "نظر",
    "qaatil": "قاتل",
    "ashk": "اشک",
    "arma": "ارما",
    "humdum": "ہمدم",
    "hamsafar": "ہمسفر",
    "rafeeq": "رفیق",
    "saaqi": "ساقی",
    "maikhana": "مے خانہ",
    "sharab": "شراب",
    "saba": "صبا",
    "bahar": "بہار",
    "khizan": "خزاں",
    "gul": "گل",
    "bulbul": "بلبل",
    "shama": "شمع",
    "parwana": "پروانہ",
    "qafas": "قفس",
    "firaaq": "فراق",
    "visaal": "وسال",
    "gamze": "غمزے",
    "kajal": "کاجل",
    "surma": "سرمہ",
    "mehndi": "مہندی",
    "sindoor": "سندور",
    "ghoonghat": "گھونگھٹ",
    "paayal": "پائل",

    # English loanwords
    "computer": "کمپیوٹر",
    "mobile": "موبائل",
    "internet": "انٹرنیٹ",
    "wiFi": "وائی فائی",
    "battery": "بیٹری",
    "charger": "چارجر",
    "screen": "اسکرین",
    "keyboard": "کی بورڈ",
    "mouse": "ماؤس",
    "printer": "پرنٹر",
    "scanner": "اسکینر",
    "camera": "کیمرہ",
    "video": "ویڈیو",
    "audio": "آڈیو",
    "music": "میوزک",
    "film": "فلم",
    "actor": "اداکار",
    "actress": "اداکارہ",
    "director": "ڈائریکٹر",
    "producer": "پروڈیوسر",
    "ticket": "ٹکٹ",
    "bus": "بس",
    "car": "کار",
    "train": "ٹرین",
    "plane": "ہوائی جہاز",
    "station": "اسٹیشن",
    "airport": "ایئرپورٹ",
    "hotel": "ہوٹل",
    "restaurant": "ریسٹورنٹ",
    "market": "مارکیٹ",

    # Religious
    "Allah": "اللہ",
    "Rasool": "رسول",
    "Quran": "قرآن",
    "Hadith": "حدیث",
    "Namaz": "نماز",
    "Roza": "روزہ",
    "Zakat": "زکوٰۃ",
    "Hajj": "حج",
    "masjid_c": "مسجد",
    "mullah": "ملا",
    "imaam": "امام",
    "muazzin": "مؤذن",
    "wudu": "وضو",
    "dua": "دعا",
    "fateha": "فاتحہ",
    "jannah": "جنت",
    "dozakh": "دوزخ",
    "shaitan": "شیطان",
    "farishta": "فرشتہ",
    "naseeb": "نصیب",
    "taqdeer": "تقدیر",

    # Legal
    "police_station": "پولیس اسٹیشن",
    "thana": "تھانہ",
    "judge": "جج",
    "vakeel": "وکیل",
    "muqadma": "مقدمہ",
    "mujrim": "مجرم",
    "saza": "سزا",
    "jail": "جیل",
    "aain": "آئین",
    "hukumat": "حکومت",
    "vazir": "وزیر",
    "sadr": "صدر",
    "wazir_e_azam": "وزیر اعظم",
    "intikhabaat": "انتخابات",
    "vote": "ووٹ",
    "jamhooriyat": "جمہوریت",
    "riyasat": "ریاست",
    "shahri": "شہری",
    "passport": "پاسپورٹ",
    "visa": "ویزا",

    # Science
    "science": "سائنس",
    "physics": "طبیعیات",
    "chemistry": "کیمسٹری",
    "biology": "حیاتیات",
    "maths": "ریاضی",
    "geometry": "ہندسہ",
    "algebra": "الجبرا",
    "history": "تاریخ",
    "geography": "جغرافیہ",
    "economics": "اقتصادیات",
    "sociology": "سماجیات",
    "psychology": "نفسیات",
    "philosophy": "فلسفہ",
    "logic": "منطق",
    "research": "تحقیق",
    "lab": "لیب",
    "experiment": "تجربہ",
    "theory": "نظریہ",
    "law": "قانون",
    "medicine": "طب",
    "engineering": "انجینئری",

    # Travel
    "safar_karna": "سفر کرنا",
    "musafir": "مسافر",
    "samaan": "سامان",
    "bag": "بیگ",
    "suitcase": "سوٹ کیس",
    "passenger": "مسافر",
    "driver": "ڈرائیور",
    "pilot": "پائلٹ",
    "captain": "کپتان",
    "map": "نقشہ",
    "compass": "قطب نما",
    "hotel_room": "ہوٹل کا کمرہ",
    "booking": "بکنگ",
    "tour": "ٹور",
    "guide": "رہنما",
    "sightseeing": "سیر و تفریح",
    "adventure": "مہم جوئی",
    "beach": "ساحل",
    "mountain": "پہاڑ",
    "desert": "صحرا",

    # Health
    "sehat": "صحت",
    "bemari": "بیماری",
    "bukhar": "بخار",
    "khansi": "کھانسی",
    "zukam": "زکام",
    "dard_sar": "درد سر",
    "dant_dard": "دانت درد",
    "operation": "آپریشن",
    "dawai": "دوا",
    "injection": "انجکشن",
    "tablet": "گولی",
    "sharbat": "شربت",
    "doctor_c": "ڈاکٹر",
    "nurse": "نرس",
    "hospital_c": "ہسپتال",
    "clinic": "کلینک",
    "ambulance": "ایمبولینس",
    "blood_pressure": "بلڈ پریشر",
    "sugar": "شوگر",
    "temperature": "درجہ حرارت",

    # Animals
    "sher": "شیر",
    "chita": "چیتا",
    "hathi": "ہاتھی",
    "ghora": "گھوڑا",
    "gaaye": "گائے",
    "bhains": "بھینس",
    "bakri": "بکری",
    "bher": "بھیڑ",
    "kutta": "کتا",
    "billi": "بلی",
    "chooha": "چوہا",
    "gilehri": "گلہری",
    "khargosh": "خرگوش",

    # Additional poetic entries
    "ishara": "اشارہ",
    "sitam": "ستم",
    "jafa": "جفا",
    "kadam": "قدم",
    "raste": "راستے",
    "rahguzaar": "رہگزار",
    "humrahi": "ہمراہی",
    "dilbar": "دلبر",
    "dildaar": "دلدار",
    "mahboob": "محبوب",
    "sanam": "صنم",
    "parwardigar": "پروردگار",
    "qismat": "قسمت",
    "aah": "آہ",
    "faryaad": "فریاد",
    "ghazal": "غزل",
    "nazm": "نظم",
    "sher": "شعر",
    "shayar": "شاعر",
    "qalam": "قلم",
    "dafatar": "دفتر",
    "shab": "شب",
    "fajr": "فجر",
    "ratjaga": "رات جاگا",
    "chandni": "چاندنی",
    "patjhad": "پت جھڑ",
    "hawain": "ہوائیں",
    "jhonka": "جھونکا",
    "shaam_e_gham": "شام غم",
    "ranj": "رنج",
    "alam": "الم",
    "aazaar": "آزار",
    "beqarari": "بے قراری",
    "iztiraab": "اضطراب",
    "karb": "کرب",
    "marham": "مرہم",
    "darman": "درمان",
    "dukh": "دکھ",
    "sukh": "سکھ",
    "musarrat": "مسرت",
    "rahat": "راحت",
    "chain": "چین",
    "qaraar": "قرار",
    "naghma": "نغمہ",
    "sargam": "سرگم",
    "raag": "راغ",
    "dhadkan": "دھڑکن",
    "sans": "سانس",
    "neend": "نیند",
    "khwab": "خواب",
    "taabeer": "تعبیر",
    "yaas": "یاس",
    "mayaasi": "مایوسی",
    "viraan": "ویران",
    "veeraana": "ویرانہ",
    "ranjish": "رنجش",
    "shikwa": "شکوہ",
    "shikayat": "شکایت",
    "gila": "گلہ",
    "malal": "ملال",
    "afsos": "افسوس",
    "hasrat": "حسرت",
    "tamanna": "تمنا",
    "justaju": "جستجو",
    "talash": "تلاش",
    "rah": "رہ",
    "raaz": "راز",
    "bhay": "بھے",
    "jaana": "جانا",
    "kehana": "کہنا",
    "muskurana": "مسکرانا",
    "roothna": "روٹھنا",
    "manaana": "منانا",
    "bicharna": "بچھڑنا",
    "tharana": "تھرنا",
    "tadapna": "تڑپنا",
    "guzarna": "گزرنا",
    "dharna": "دھرنا",
    "latakna": "لٹکنا",
    "bali": "بچی",
    "yaar": "یار",
    "sathi": "ساتھی",
    "humdam": "ہمدرد",
    "dukhi": "دکھی",
    "pareshan": "پریشان",
    "ghamgeen": "غمین",
    "shaad": "شاد",
    "maayoos": "مایوس",
    "nakaam": "ناکام",
    "kamiyaab": "کامیاب",
    "mukammal": "مکمل",
    "adhoora": "ادھورا",
    "tareek": "تاریک",
    "pur_kaar": "پرکار",
    "be_kaar": "بیکار",
    "rangin": "رنگین",
    "haseen": "حسین",
    "jameel": "جمیل",
    "khubsurat": "خوبصورت",
    "badsurat": "بدصورت",
    "ajeeb": "عجیب",
    "ghaflat": "غفلت",
    "hosh": "ہوش",
    "behosh": "بے ہوش",
    "khayal": "خیال",
    "waswas": "وسواس",
    "shak": "شک",
    "yaqeen": "یقین",
    "guman": "گمان",
    "qadar": "قدر",
    "izzat": "عزت",
    "ruswa": "رسوا",
    "naam": "نام",
    "nishaan": "نشان",
    "pata": "پتہ",
    "thikana": "ٹھکانہ",
    "ghar": "گھر",
    "vatan": "وطن",
    "des": "دیس",
    "pardes": "پردیس",
    "dag": "داغ",
    "zakhm": "زخم",
    "ragh": "رگ",
    "nas": "نس",
    "aankhon mein": "آنکھوں میں",
    "lab par": "لب پر",
    "dil mein": "دل میں",
    "rukh se": "رخ سے",
    "baat": "بات",
    "alfaz": "الفاظ",
    "lafz": "لفظ",
    "misra": "مصرعہ",
    "qafiya": "قافیہ",
    "radeef": "ردیف",
    "matla": "مطلع",
    "maqta": "مقطع",
    "takhallus": "تخلص",

    # Another 200+ entries
    "aaina": "آئینہ",
    "nasheman": "آشیانہ",
    "barg": "برگ",
    "shakh": "شاخ",
    "daman": "دامن",
    "daaman": "دامن",
    "garebaan": "گریباں",
    "jigar": "جگر",
    "deeda": "دیدہ",
    "mizhga": "مژگاں",
    "rukhsaar": "رخسار",
    "zulf": "زلف",
    "gesu": "گیسو",
    "kakul": "کاکل",
    "payambar": "پیغمبر",
    "rusool": "رسول",
    "murshid": "مرشد",
    "deewana": "دیوانہ",
    "mast": "مست",
    "mai": "مے",
    "jaam": "جام",
    "saghar": "ساغر",
    "meena": "مینا",
    "bada": "بڑا",
    "masti": "مستی",
    "nasha": "نشہ",
    "bekaar": "بیکار",
    "darbadar": "دربدر",
    "mukhbari": "مخبری",
    "paighaam": "پیغام",
    "qasid": "قاصد",
    "khat": "خط",
    "ruqaa": "رقاع",
    "tahrir": "تحریر",
    "aawaz": "آواز",
    "sada": "صدا",
    "gunj": "گنج",
    "goonj": "گونج",
    "sookha": "سوکھا",
    "tar": "تر",
    "nam": "نم",
    "numa": "نما",
    "benam": "بے نام",
    "badnaam": "بدنام",
    "sitara_ha": "ستارے",
    "khurshid": "خورشید",
    "mehtaab": "مہتاب",
    "anjum": "انجم",
    "falak": "فلک",
    "gardoon": "گردوں",
    "qamar": "قمر",
    "zamee": "زہرہ",
    "khaak": "خاک",
    "gard": "گرد",
    "shor": "شور",
    "ghul": "غول",
    "gubar": "غبار",
    "dhuwan": "دھواں",
    "shola": "شعلہ",
    "roshni": "روشنی",
    "ujala": "اجالا",
    "chiragh": "چراغ",
    "diya": "دیہ",
    "deep": "دیپ",
    "phool_jhaari": "پھول جھاڑی",
    "kali": "کلی",
    "kuinchi": "کونچ",
    "deh": "دیہ",
    "gaaon": "گاؤں",
    "basti": "بستی",
    "nagar": "نگر",
    "nagri": "نگری",
    "raah": "راہ",
    "raah_e": "راہِ",
    "rahgir": "راہگیر",
    "karwaan": "کارواں",
    "qaafila": "قافلہ",
    "manzil_hr": "منزل",
    "rah_ro": "رہ رو",
    "gird": "گرد",
    "laash": "لاش",
    "jasad": "جسد",
    "kaifiyat": "کیفیت",
    "haal": "حال",
    "jazba": "جذبہ",
    "dil_dari": "دل داری",
    "dil_geer": "دل گیر",
    "dil_shikasta": "دل شکستہ",
    "dil_shikan": "دل شکن",
    "soz": "سوز",
    "gudaz": "گداز",
    "navaa": "نوا",
    "naala": "نالہ",
    "baar": "بار",
    "bala": "بالا",
    "aafaat": "آفات",
    "balaa": "بلا",
    "ghamzada": "غم زدہ",
    "ranj_urdu": "رنج",
    "malaal": "ملال",
    "naadaan": "نادان",
    "ahmaq": "احمق",
    "saada": "سادہ",
    "saada_looh": "سادہ لوح",
    "khaalis": "خالص",
    "nirdosh": "نردوش",
    "gunah": "گناہ",
    "bakhshna": "بخشنا",
    "maaf_karna": "معاف کرنا",
    "rahem": "رحم",
    "reham": "ریحم",
    "karam": "کرم",
    "ehesaan": "احسان",
    "shukr": "شکر",
    "shukriya": "شکریہ",
    "tashakur": "تذکیر",
    "hazir": "حاضر",
    "ghaeb": "غائب",
    "gum": "گم",
    "pa": "پا",
    "paana": "پانا",
    "khona": "کھونا",
    "mil_jaana": "مل جانا",
    "bichharna": "بچھڑنا",
    "lootna": "لوٹنا",
    "lutaana": "لٹانا",
    "ga_na": "گانا",
    "sunaa": "سنا",
    "dekhna": "دیکھنا",
    "takna": "تکنا",
    "ghur_se": "گھور سے",
    "jhaankna": "جھانکنا",
    "chhupna": "چھپنا",
    "chhupana": "چھپانا",
    "ro_dena": "رو دینا",
    "hans_dena": "ہنس دینا",
    "muskar_dena": "مسکر دینا",
    "chal_dena": "چل دینا",
    "bhagna": "بھاگنا",
    "bhaagna": "بھاگنا",
    "aankh_se": "آنکھ سے",
    "nazar_se": "نظر سے",
    "nigah_se": "نگاہ سے",
    "chehre_par": "چہرے پر",
    "honton_pe": "ہونٹوں پے",
    "sanson_mein": "سانسوں میں",
    "dharkanon_mein": "دھڑکنوں میں",
    "kabhi": "کبھی",
    "kabhi_kabhi": "کبھی کبھی",
    "aksar": "اکثر",
    "ab": "اب",
    "tab": "تب",
    "jab": "جب",
    "kab": "کب",
    "yahan": "یہاں",
    "wahan": "وہاں",
    "kahan": "کہاں",
    "idhar": "ادھر",
    "udhar": "ادھر",
    "kidhar": "کدھر",
    "kitna": "کتنا",
    "jitna": "جتنا",
    "itna": "اتنا",
    "thoda": "تھوڑا",
    "zyada": "زیادہ",
    "bohot": "بہت",
    "kafi": "کافی",
    "bilkul": "بلکل",
    "sab_kuch": "سب کچھ",
    "kuch_bhi": "کچھ بھی",
    "kuch_na": "کچھ نا",
    "jaisa": "جیسا",
    "waisa": "ویسا",
    "aisa": "ایسا",
    "kaisa": "کیسا",
    "jaise": "جیسے",
    "waise": "ویسے",
    "jaisey": "جیسے",
    "woh_l": "وہ",
    "yeh_l": "یہ",
    "main_p": "میں",
    "ham_p": "ہم",
    "apna_p": "اپنا",
    "tera": "تیرا",
    "mera": "میرا",
    "uska": "اسکا",
    "inka": "انکا",
    "unki": "انکی",
    "jinki": "جنکی",
    "jiska": "جسکا",
    "jin_ko": "جن کو",
    "jis_se": "جس سے",
    "jin_mein": "جن میں",
    "jis_par": "جس پر",
    "jin_ka": "جن کا",
    "ji_haan": "جی ہاں",
    "nahi": "نہیں",
    "mat": "مت",
    "shayed": "شاید",
    "to": "تو",
    "ki_oor": "کیوں",
    "kis_liye": "کسی لیے",
    "kya": "کیا",
    "na": "نا",
    "haan": "ہاں",
    "jee": "جی",
    "beshak": "بیشک",
    "albatta": "البظا",
    "yaqeenan": "یقینا",
    "goya": "گویا",
    "mann": "من",
    "dil_se": "دل سے",
    "jaan_se": "جان سے",
    "chaar_su": "چار سو",
    "chaar_taraf": "چار طرف",
    "ek_taraf": "ایک طرف",
    "do_pahar": "دو پہر",
    "teen_pahar": "تین پہر",
    "seh": "سہ",
    "paanch_p": "پانچ",
    "chay": "چھے",

    # dil_ruba etc.
    "dil_ruba": "دل ربا",
    "dil_fareb": "دل فریب",
    "dil_awar": "دل آوار",
    "dil_sitani": "دل ستانی",
    "dil_azeeb": "دل عذیب",
    "dil_nashiin": "دل نشیں",
    "dil_kash": "دل کش",
    "jaan_far": "جان فر",
    "jaan_nisaar": "جان نثار",
    "jaan_ba_laab": "جان با لب",
    "jaan_raba": "جان ربا",
    "jaan_sitaan": "جان ستان",
    "ruh": "روح",
    "ruhaani": "روحانی",
    "ruh_afza": "روح افزا",
    "ruh_geer": "روح گیر",
    "ruh_nawaaz": "روح نواز",
    "shab_e_furqat": "شب فرقت",
    "shab_e_hijr": "شب ہجر",
    "shab_e_vida": "شب وداع",
    "shab_e_visaal": "شب وصال",
    "subh_e_azal": "صبح ازل",
    "subh_e_ummeed": "صبح امید",
    "shaam_e_ghurbat": "شام غربت",
    "shaam_e_visaal": "شام وصال",
    "fajar": "فجر",
    "jahan": "جہاں",
    "jahan_aan": "جہاں آراء",
    "jahan_geer": "جہاں گیر",
    "jahan_numaa": "جہاں نما",
    "kainaat": "کائنات",
    "kaunain": "کونین",
    "zamaana": "زمانہ",
    "zamaane": "زمانے",
    "rauzan": "روزن",
    "raughan": "راوگن",
    "kunj": "کنج",
    "kunj_e_jigar": "کنج جگر",
    "kunj_e_dil": "کنج دل",
    "jhoomar": "جھومر",
    "jhalar": "جھالر",
    "kamar": "کمر",
    "qaba": "قبہ",
    "qabaa": "قبا",
    "taj": "تاج",
    "takht": "تخت",
    "taj_daar": "تاج دار",
    "taj_posh": "تاج پوش",
    "jalaal": "جلال",
    "jamaal": "جمال",
    "jalaal_o_jamaal": "جلال و جمال",
    "husn_o_ishq": "حسن و عشق",
    "ishq_o_mohabbat": "عشق و محبت",
    "dard_o_gham": "درد و غم",
    "aah_o_faryaad": "آہ و فریاد",
    "naala_o_fariyaad": "نالہ و فریاد",
    "lab_khama": "لب خامہ",
    "lab_goya": "لب گویا",
    "lab_basta": "لب بستہ",
    "lab_kushada": "لب کشادہ",
    "dil_basta": "دل بستہ",
    "dil_kushada": "دل کشادہ",
    "dil_tang": "دل تنگ",
    "dil_gudaaz": "ل گداز",
    "dil_saaz": "دل ساز",
    "dil_nawaaz": "دل نواز",
    "dil_nashin": "دل نشین",
    "dil_pazeer": "دل پذیر",
    "jaan_gudaaz": "جان گداز",
    "jaan_saaz": "جان ساز",
    "jaan_nawaaz": "جان نواز",
    "jaan_nishaan": "جان نشان",
    "jaan_pazeer": "جان پذیر",
    "jaan_fiza": "جان فزا",
    "jaan_afreen": "جان آفرین",
    "jaan_farsa": "جان فرسا",
    "raah_farsa": "راہ فرسا",
    "rah_e_manzil": "راہ منزل",
    "rah_e_ishq": "راہ عشق",
    "rah_e_wafa": "راہ وفا",
    "rahzan": "رہزن",
    "raah_gir": "راہ گیر",
    "raah_rau": "راہ رو",
    "raah_bin": "راہ بین",
    "raah_bar": "راہ بر",
    "raah_numa": "راہ نما",
    "raah_zan": "راہ زن",
    "raah_pai": "راہ پئے",
    "raah_o_resm": "راہ و رسم",
    "resm": "رسم",
    "riwaaj": "رواج",
    "rivayat": "روایت",
    "riwaayat": "روایت",
    "dastoor": "دستور",
    "dastoor_e_zindagi": "دستور زندگی",
    "dastoor_e_mohabbat": "دستور محبت",
    "dastoor_e_wafa": "دستور وفا",
    "dastoor_e_junoon": "دستور جنون",
    "aap_baiti": "آپ بیتی",
    "jaga_baiti": "جاگ بیتی",
    "raat_baiti": "رات بیتی",
    "din_baiti": "دن بیتی",

    # 100 new words (first batch)
    "be_khudi": "بے خودی",
    "be_hoshi": "بے ہوشی",
    "be_zabaan": "بے زبان",
    "be_asar": "بے اثر",
    "be_chain": "بے چین",
    "be_qaraar": "بے قرار",
    "be_sabab": "بے سبب",
    "be_wafa": "بے وفا",
    "be_parwah": "بے پرواہ",
    "be_gunaah": "بے گناہ",
    "be_imtihaan": "بے امتحان",
    "be_intiha": "بے انتہا",
    "be_misaal": "بے مثال",
    "be_nazar": "بے نظر",
    "be_nisha": "بے نشہ",
    "be_khata": "بے خطا",
    "be_shak": "بے شک",
    "be_khabar": "بے خبر",
    "be_hijaab": "بے حجاب",
    "be_haya": "بے حیا",
    "ba_wafa": "با وفا",
    "ba_shak": "با شک",
    "ba_khabar": "با خبر",
    "ba_hijaab": "با حجاب",
    "ba_izzat": "با عزت",
    "ba_qadar": "با قدر",
    "ba_tamaam": "با تمام",
    "ba_shaoor": "با شعور",
    "ba_hosh": "با ہوش",
    "ba_hiwaas": "با حواس",
    "dardnaak": "دردناک",
    "ghamnaak": "غمناک",
    "dil_saaz_adj": "دل ساز",
    "dil_soz": "دل سوز",
    "dil_azeem": "دل عظیم",
    "dil_pazeer_adj": "دل پذیر",
    "jaan_kah": "جان کہ",
    "jaan_bah": "جان بہ",
    "jaan_soz": "جان سوز",
    "jaan_aazaar": "جان آزار",
    "gul_andaam": "گل اندام",
    "gul_rukh": "گل رخ",
    "gul_badn": "گل بدن",
    "gul_chehra": "گل چہرہ",
    "gul_rakh": "گل رخ",
    "mah_rukh": "ماہ رخ",
    "mah_liqaa": "ماہ لقا",
    "mah_paikar": "ماہ پیکر",
    "mah_jabeen": "ماہ جبیں",
    "shab_gir": "شب گیر",
    "shab_zindagi": "شب زندگی",
    "shab_nam": "شب نم",
    "shab_zameer": "شب ضمیر",
    "subh_geer": "صبح گیر",
    "subh_dam": "صبح دم",
    "subh_naash": "صبح ناش",
    "subh_baan": "صبح بان",
    "salasil": "سلاسل",
    "zanjir": "زنجیر",
    "zabt": "ضبط",
    "zabt_naash": "ضبط ناش",
    "fana": "فنا",
    "baqa": "بقا",
    "fana_fi_Allah": "فنا فی اللہ",
    "baqa_bi_Allah": "بقا باللہ",
    "tajalli": "تجلی",
    "tajrid": "تجرد",
    "tarkeeb": "ترکیب",
    "taqreeb": "تقریب",
    "taqreer": "تقریر",
    "izhaar": "اظہار",
    "zahoor": "ظہور",
    "zameer": "ضمیر",
    "zameer_naak": "ضمیر ناک",
    "fitrat": "فطرت",
    "fitarat": "فطرت",
    "jibillat": "جبلت",
    "wijdan": "وجدان",
    "wijdani": "وجدانی",
    "raaz_o_niaz": "راز و نیاز",
    "raaz_daari": "راز داری",
    "raaz_daan": "راز دان",
    "raaz_go": "راز گو",
    "raaz_shanas": "راز شناس",
    "niyaz": "نیاز",
    "niyazmand": "نیازمند",
    "aashna": "آشنا",
    "aashnaai": "آشنائی",
    "begana": "بیگانہ",
    "beganagi": "بیگانگی",
    "ham_nawa": "ہم نوا",
    "ham_raaz": "ہم راز",
    "ham_dard": "ہم درد",
    "ham_dam": "ہم دم",
    "ham_saaya": "ہم سایہ",
    "ham_zulf": "ہم زلف",
    "ham_sukhan": "ہم سخن",
    "ham_qadam": "ہم قدم",
    "hum_nashin": "ہم نشین",
    "hum_khayal": "ہم خیال",
    "rashk": "رشک",
    "ghairat": "غیرت",
    "ghairatmand": "غیرت مند",

    # 100 NEW WORDS (second batch, no duplicates)
    "aafat": "آفت",
    "aahang": "آہنگ",
    "aaraam_dil": "آرام دل",
    "aas": "آس",
    "abroo": "آبرو",
    "ada": "ادا",
    "adab": "ادب",
    "adawat": "عداوت",
    "aesaar": "ایثار",
    "afaq": "آفاق",
    "afsurdagi": "افسردگی",
    "ahtram": "احترام",
    "aju": "اجو",
    "alam_e_gham": "عالم غم",
    "alif": "الف",
    "amaan": "امان",
    "amal": "عمل",
    "ana": "انا",
    "anmol": "انمول",
    "ard": "ارد",
    "asar": "اثر",
    "asooda": "آسودہ",
    "atish": "آتش",
    "atr": "عطر",
    "awaaz_dena": "آواز دینا",
    "azab": "عذاب",
    "baab": "باب",
    "bahaduri": "بہادری",
    "bahaar_naak": "بہار ناک",
    "bala_e_gham": "بلائے غم",
    "bandagi": "بندگی",
    "barish_naak": "بارش ناک",
    "basta": "بستہ",
    "be_noor": "بے نور",
    "be_raah": "بے راہ",
    "be_saaz": "بے ساز",
    "be_shuba": "بے شبہ",
    "be_waqt": "بے وقت",
    "buraai": "برائی",
    "chashm": "چشم",
    "dagh_naak": "داغ ناک",
    "dagh_daar": "داغ دار",
    "dard_geer": "درد گیر",
    "dardnaak_poem": "دردناک",
    "daulat": "دولت",
    "dil_kush": "دل کش",
    "dil_nawaaz_poetic": "دل نواز",
    "dua_go": "دعا گو",
    "faqeer": "فقیر",
    "fard": "فرد",
    "faza": "فضا",
    "garaj": "گرج",
    "ghair": "غیر",
    "gham_geeri": "غم گیری",
    "gham_naak": "غم ناک",
    "ghazab": "غضب",
    "ghina": "غنا",
    "gul_fam": "گل فام",
    "gul_naar": "گل نار",
    "gul_raan": "گل رعن",
    "gulshan_e_jaan": "گلشن جان",
    "haal_dil": "حال دل",
    "haalat": "حالت",
    "hijab": "حجاب",
    "hijr_naak": "ہجر ناک",
    "hum_nawa_poetic": "ہم نوا",
    "hum_raaz_poetic": "ہم راز",
    "hum_saaz": "ہم ساز",
    "husn_parast": "حسن پرست",
    "iman": "ایمان",
    "intezaar": "انتظار",
    "ishq_bazi": "عشق بازی",
    "ishq_daari": "عشق داری",
    "jaan_geeri": "جان گیری",
    "jaan_kufur": "جان کفر",
    "jaan_layaq": "جان لایق",
    "jaan_naak": "جان ناک",
    "jaan_parvar": "جان پرور",
    "jaan_pehchan": "جان پہچان",
    "jaan_sitani": "جان ستانی",
    "jaan_war": "جان ور",
    "kabood": "کبود",
    "karvaan": "کارواں",
    "kashish": "کشش",
    "kharaab": "خراب",
    "kharaab_haal": "خراب حال",
    "khushi_naak": "خوشی ناک",
    "lab_ba_lab": "لب بہ لب",
    "lab_parast": "لب پرست",
    "lab_ravez": "لب ریز",
    "lazzat": "لذت",
    "maalik": "مالک",
    "mani": "معنی",
    "maqtal": "مقتل",
    "marhaam": "مرہم",
    "mauj": "موج",
    "mayoos": "مایوس",
    "meel": "میل",
    "mehmaan": "مہمان",
    "mushkil": "مشکل",
    "mutmain": "مطمئن",
    "wo": "وہ",
     "tu": "تو",
    "khusbo":"خوشبو",
    "hy":"ہے",
     "hamary":"ہمارے",
     "baad":"بعد",
      "bad":"بعد",
    "mery":"میرے",
      "mohabat":"محبت",
      "tarsh":"ترش",
      "tarash":"ترش",
     "jao":"جاو",
       "gay":"گے",
    "gy":"گے",
    "tumhary":" تمھارے",
      "baghir":" بغیر",


}


def roman_to_urdu(text: str) -> str:
    """
    Convert a Roman Urdu string to Urdu script.
    Preserves words not in the map as is.
    """
    if not text:
        return text

    words = text.lower().split()
    converted = [ROMAN_MAP.get(word, word) for word in words]
    return " ".join(converted)


def contains_roman(text: str) -> bool:
    """
    Detect if the string contains Latin characters (Roman Urdu).
    """
    if not text:
        return False
    # If any ASCII letter is present, assume Roman
    return any(ord(c) < 128 and c.isalpha() for c in text)